minimumReleaseAgeExcludePrune: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver
  - "@vercel/cli-config@0.2.4"
  - "@vercel/oidc@3.8.5"
  - "@vercel/cli-exec@1.0.1"

shellEmulator: true

allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  unrs-resolver: true
  vue-demi: true

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - unrs-resolver
  - vue-demi
